### ISSUE TITLE
caching the length of the array will make this faster. 

### ISSUE THREAD

**Issue by aric87** [danj707/foodme#12]
here: 
https://github.com/danj707/foodme/blob/master/public/app.js#L174
 you have: 
`for(var i=0;i<result[key].length;i++) {`

Each time the loop runs, the code has to get the length of result[key] before determining if it's greater than i. 
You can store the length in a variable when the loop starts to make this more efficient: 
`for(var i=0, j=result[key].length ; i< j ;i++) {`

**Comment by danj707** [comment]
Awesome, I didn't even know you could do this!  Updated several for loops to include this caching!
