### ISSUE TITLE
move the "send mail" higher

### ISSUE THREAD

**Issue by aric87** [danj707/foodme#6]
if you try to send the email before creating the user, you can validate that the email exists. If the email fails, you shoud return an error to the user, and not create the account.

**Comment by danj707** [comment]
Another email issue, I'm not actually verifying any email addresses, and the mailgun account I have doesn't do emailing to non-verified accounts.  So, i've set it to myself.  When a user signs up, I get an email essentially. But, in future releases, yes, I'd be verifying emails are sent to a correct email address PRIOR to creating the account.  So for now, i'm going to leave it.  But in the future, i'd move it. :-)
